elk:
  image: sebp/elk
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  volumes:
  - elk-data:/var/lib/elasticsearch
  restart: always
  labels:
    app: purplebureau
    io.rancher.container.pull_image: always
