.catalog:
  name: Orchtech - ELK
  version: full-bundle
  description: ElasticSearch - Logstash - Kibana

elk:
  scale: 1
  health_check:
    port: 9200
    interval: 2000
    initializing_timeout: 180000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
